CREATE TABLE SCHEDULE(
SNUM NUMBER(10),
ID  VARCHAR2(20), --회원아이디
IID VARCHAR2(20), --강사아이디
STARTDATE NUMBER(20),
ENDDATE  NUMBER(20),
ATTENDANCE NUMBER(2),
COLOR VARCHAR2(20),
PRIMARY KEY(SNUM),
FOREIGN KEY(ID) REFERENCES USERS ON DELETE CASCADE
);

CREATE SEQUENCE SCHEDULE_SEQ;