CREATE TABLE LOCKER
(
LNUM NUMBER(10) PRIMARY KEY,
NUM NUMBER(10) REFERENCES KEY USERS(NUM),
SEX VARCHAR2(20),
RENT VARCHAR2(20),
RENTSTART DATE,
RENTEND DATE
);
insert into locker 
values(1,0,'남자','사용',sysdate,null);
commit;